config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  devise_for :users
  root to: 'pages#index'
  #home page to access to other area
  get 'profile/user/:id', to: 'profiles#show', as: 'profile'
  get 'profile/edit', to: 'profiles#edit'
  put 'profile', to: 'profiles#update'
  patch 'profile', to: 'profiles#update'
  match 'profile/user/:id' => 'profiles#update', via: :patch

  #user_profile should only be deleted if account is no longer exists
  resources :listings
  get 'cart', to: 'carts#show'
  resources :cart_items
  resources :messages
  get "/payments/session", to: "payments#get_stripe_id"
  post "/payments/webhook", to: "payments#webhook"
  get "/payments/success", to: "payments#success"
  resources :orders, only: [:index, :show]
  post "/set_location", to: "pages#set_location"
  get "/remove_location", to: "pages#remove_location"
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :profile, optional: true
  belongs_to :product
  has_one_attached :image
  has_many :messages
  has_many :cart_items
  has_many :carts, through: :cart_items
  validates :title, presence: true, length: { in: 3..40 }
  validates :description, presence: true, length: { in: 6..200 }
  validates :price, presence: true, numericality: true, inclusion: { in: 0.01..100 }

  enum delivery: { "Local Pickup": 1, "Delivery": 2, "Both": 3 }
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :set_profile, only: [:create, :destroy]
  authorize_resource

  def index
    ## If user using the search title function
    if params[:search]
      ## Searches listings table and selects listing if listing matches the search keyword and is not closed
      ## Includes image record for the selected record
      @listings = Listing.with_attached_image.where("lower(title) LIKE ?", "%#{params[:search].downcase}%").where(closed: false)
      check_nil?
    ## If there is a geolocation stored in the cookie
    elsif cookies[:lat_lon]
      ## Convert cookies back to an array
      user_location = JSON.parse cookies[:lat_lon]
      ## Searches any user near the user_location and only return profile id
      nearby_user = Profile.near(user_location, 12, units: :km).reorder('').pluck(:id)
      ## Searches and returns listings if profile id matches the array of id
      ## Includes image record for the selected record
      @listings = Listing.with_attached_image.where(profile_id: nearby_user, closed: false).order(created_at: :desc)
      check_nil?
      ## if there is geolocation stored and user used the filter function
      if params[:filter]
        ## alter @listings with filter
        @listings = @listings.where(product_id: params[:filter], closed: false).order(created_at: :desc)
        check_nil?
      end
    ## User uses the filter function without a stored location
    elsif params[:filter]
      ## Searches
      ## Includes image record for the selected record
      @listings = Listing.with_attached_image.where(product_id: params[:filter], closed: false).order(created_at: :desc)
      check_nil?
    else
      ## Inludes image record for the selected record
      @listings = Listing.with_attached_image.where(closed: false).order(created_at: :desc)
    end
  end

  def show
  end

  def new
    profile_blank?
    @listing = Listing.new
  end

  def create
    @listing = @profile.listings.create(listing_params)
    if @listing.errors.any?
      render :new
    else
      flash[:success] = "You successfully created a new listing!"
      redirect_to @listing
    end
  end

  def edit
  end

  def update
    if @listing.update(listing_params)
      redirect_to listing_path(@listing.id)
    else
      render :edit
    end
  end

  def destroy
    if @listing.carts.length == 0
      @listing.destroy
      flash[:success] = "Listing deleted successfully"
    else
      @listing.closed = true
      if @listing.save
        flash[:alert] = "Listing cannot be deleted but is now closed"
      end
    end
    redirect_to profile_path(@profile.id)
  end

  private

  def set_listing
    @listing = Listing.find(params[:id])
  end

  def listing_params
    params.require(:listing).permit(:title, :description, :price, :image, :delivery, :product_id)
  end

  def check_nil?
    if @listings.length < 1
      flash.now[:alert] = "No matching result found"
      @listings = Listing.with_attached_image.where(closed: false).order(created_at: :desc)
    end
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
  def item_location(listing)
    geocode = Profile.find(listing.profile_id).to_coordinates
    location = Geocoder.search(geocode).first
    location.suburb + ", " + location.state
  end

  def img_for(listing)
    if listing.image.present?
      listing.image
    else
      'default.jpeg'
    end
  end
end

app/views/listings/_card.html.erb
<%= link_to listing, class:"text-decoration-none text-dark" do %>
<div class="card mb-3" style="max-width: 540px; width: 60vw; height: 20vh ">
  <div class="row no-gutters">
    <div class="col-md-4">
      <img src="..." class="card-img" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= listing.title %></h5>
        <p class="card-text"><%= listing.description %></p>
        <p class="card-text"><small class="text-muted"><%= listing.created_at %></small></p>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/listings/_form.html.erb
<%= form_with model: listing, local: true do |form| %>
<div class="form-group">
  <%= form.label :title %>
  <%= form.text_field :title, class: "form-control" %>
</div>
<div class="form-group">
  <%= form.label :description %>
  <%= form.text_area :description, class: "form-control" %>
</div>
<div class="form-group row">
  <%= form.label :price, class: "col-sm-2 col-form-label" %>
  <div class="row">
    <div class="col">
      <%= form.number_field :price, min: 0, step: 0.01, class: "form-control" %>
     </div>
     <div class="col">
      <p>per unit<p>
      </div>
  </div>      
</div>
<div class="form-group row">
  <%= form.label :product_type, class:"col-sm-2 col-form-label" %>
  <%= form.collection_select(:product_id, Product.all, :id, :name) %>
</div>
<fieldset class="form-group">
    <div class="row">
      <legend class="col-form-label col-sm-2 pt-0">Delivery Options</legend>
      <div class="col-sm-10">
        <div class="form-check">
          <input class="form-check-input" type="radio" name="listing[delivery]" id="delivery" value="Local Pickup" checked>
          <label class="form-check-label" for="gridRadios1">
            Local Pickup
          </label>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="radio" name="listing[delivery]" id="delivery" value="Delivery">
          <label class="form-check-label" for="gridRadios2">
            Delivery
          </label>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="radio" name="listing[delivery]" id="delivery" value="Both" >
          <label class="form-check-label" for="gridRadios3">
            both
          </label>
        </div>
      </div>
    </div>
  </fieldset>

  <div class="form-group">
  <%= form.label :image %> 
  <%= form.file_field :image, accept: 'image/png,image/gif,image/jpeg,image/jpg', class:"form-control-file" %>
</div>
  <div class="form-group row">
    <div class="col-sm-10">
      <%= form.submit class: "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/listings/_listing_template.html.erb
<div class="row content mt-3">
<% if flash[:unsuccess] %>
<p><%= flash[:unsucess] %></p>
<% end %>
  <div class="col-md-4">
    <%=image_tag url_for(img_for(listing)), alt: "#{listing.title} image", class: 'mt-2', style: 'width:100%;' %>
  </div>
  <div class="col-md-8">
    <h1><%= listing.title %></h1>
    <div>
      <strong>Product type:  </strong>
      <span><%= listing.product.name %></span>
    </div>
    <div>
      <strong>Location:  </strong>
      <span><%= item_location(listing) %></span>
    </div>
    <div>
      <strong>Pickup/Delivery:  </strong>
      <span><%= listing.delivery %></span>
    </div>
    <div>
      <strong>Price:  </strong>
      <span><%= "$""%.2f" % listing.price %></span>
    </div>

    <% unless account_owner?(listing) || listing.closed == true%>
      <%= form_with model: CartItem.new, local: true, method: :post do |form| %>
        <%= form.number_field :quantity, size: "4", step: 1, value: 1, min: 1, max: 100 %>
        <%= form.hidden_field :listing_id, value: @listing.id %>
        <%= form.submit "Add to basket" %><% end %>
        <% if flash[:bought] %>
          <span><%= flash[:bought] %></span>
      <% end %>
    <% end %>
    <p><%= listing.description %></p>
    <%= link_to 'Back', listings_path, class: 'btn btn-success' %> 
     <% if (can? :manage, @listing) && (listing.closed == false) %>
      <%= link_to 'Edit', edit_listing_path(@listing), class: 'btn btn-info' %>
      <%= link_to "Delete", listing_path(@listing), method: :delete, class: "btn btn-danger", data: { confirm: "Really delete #{@listing.title}?"} %>
    <% end %>
    
    <div>
      <span class="font-italic" >Listed by <strong><%= link_to listing.profile.user.username, profile_path(listing.profile.id) %></strong> on <%= listing.created_at.to_formatted_s(:long) %></span>
    </div>
  </div>
</div>

app/views/listings/_sidebar.html.erb
<nav class="sidebar">
  <ul class="list-group">
    <li class="list-group-item list-group-item-success text-center">Search Criteria</li>
    <li class="list-group-item">
      <form class="form-inline", action="/set_location", method="post">
      <input class="form-control input-sm" type="search" placeholder="123 New st, Newtown" aria-label="Search", name="address" required="required" minlength="8" value="<%= stored_location %>">
      <button class="btn my-2 my-sm-0 btn-sm text-success" type="submit">Search</button>
      <% if cookies[:lat_lon] %>
        <%= link_to "Remove saved location", {controller: "pages", action: "remove_location"}, class: "text-muted font-italic remove_link" %>
      <% end %>
    </li>
    <li class="list-group-item "><%= link_to "Vegetables", listings_path(filter: 1) %></li>
    <li class="list-group-item"><%= link_to "Fruits", listings_path(filter: 2) %></li>
    <li class="list-group-item"><%= link_to "Herbs", listings_path(filter: 3) %></li>
    <li class="list-group-item"><%= link_to "Eggs", listings_path(filter: 4) %></li>
    <li class="list-group-item"><%= link_to "Honey", listings_path(filter: 5) %></li>
    <li class="list-group-item"><%= link_to "Mushroom", listings_path(filter: 6) %></li>
    <li class="list-group-item"><%= link_to "View all", listings_path %></li>
  </ul>
</nav>

app/views/listings/edit.html.erb
<%= render 'shared/form_errors', resource: @listing %>
<div class="container">
  <h1>Edit existing listing</h1>
  <%= render "form", listing: @listing %>
</div>
<div class="placeholder"></div>

app/views/listings/index.html.erb
<%= render 'shared/flash'%>
  <div class="listing_container">
    <%= render "sidebar"%>
    <div class="container">
      <div class="listings">
        <% @listings.each do |listing| %>
          <%= render 'shared/card', listing: listing %>
        <% end %>
      </div>
    </div>
  </div>
<div class="placeholder"></div>

app/views/listings/new.html.erb
<%= render 'shared/form_errors', resource: @listing %>
<div class="container">
  <h1>Create new listing</h1>
  <%= render "form", listing: @listing %>
</div>
<div class="placeholder"></div>

app/views/listings/show.html.erb
<%= render 'shared/flash'%>
<div class="container">
  <%= render "listing_template", listing: @listing%>
</div>
<div class="placeholder"></div>