config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  devise_for :users
  root to: 'pages#index'
  #home page to access to other area
  get 'profile/user/:id', to: 'profiles#show', as: 'profile'
  get 'profile/edit', to: 'profiles#edit'
  put 'profile', to: 'profiles#update'
  patch 'profile', to: 'profiles#update'
  match 'profile/user/:id' => 'profiles#update', via: :patch

  #user_profile should only be deleted if account is no longer exists
  resources :listings
  get 'cart', to: 'carts#show'
  resources :cart_items
  resources :messages
  get "/payments/session", to: "payments#get_stripe_id"
  post "/payments/webhook", to: "payments#webhook"
  get "/payments/success", to: "payments#success"
  resources :orders, only: [:index, :show]
  post "/set_location", to: "pages#set_location"
  get "/remove_location", to: "pages#remove_location"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can [:read, :create], Listing
    if user.present?
      can :manage, Listing, profile_id: user.profile.id
      can :manage, Profile, user_id: user.id
      if user.admin?
        can :manage, :all
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :profile
  has_many :cart_items
  has_many :listings, through: :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :listing
  validates :quantity, numericality: true, inclusion: { in: 1..100 }
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :profile, optional: true
  belongs_to :product
  has_one_attached :image
  has_many :messages
  has_many :cart_items
  has_many :carts, through: :cart_items
  validates :title, presence: true, length: { in: 3..40 }
  validates :description, presence: true, length: { in: 6..200 }
  validates :price, presence: true, numericality: true, inclusion: { in: 0.01..100 }

  enum delivery: { "Local Pickup": 1, "Delivery": 2, "Both": 3 }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: 'Profile', foreign_key: 'sender_id'
  belongs_to :recipient, class_name: 'Profile', foreign_key: 'recipient_id'
  belongs_to :listing, optional: true
  has_many :attached_messages, class_name: "Message", foreign_key: "thread_id"
  belongs_to :thread, class_name: "Message", optional: true
  validates :body, presence: true, length: { in: 3..500 }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :profile
  has_many :order_items, dependent: :destroy
  has_many :listings, through: :order_items

  enum delivery: { "Local Pickup": 1, "Delivery": 2 }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :listing
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :listings
  has_many :subcategories, class_name: "Product", foreign_key: "category_id"
  belongs_to :category, class_name: "Product", optional: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one :cart, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :listings
  validates :first_name, presence: true, length: { minimum: 2 }
  validates :last_name, presence: true, length: { minimum: 2 }
  validates :address_line1, presence: true, length: { minimum: 5 }
  validates :suburb, :state, presence: true
  validates :postcode, presence: true, length: { is: 4 }
  geocoded_by :address
  after_validation :geocode_or_reset_coordinates, if: :address_line1_changed?
  after_create :init_cart

  private

  def init_cart
    self.create_cart
  end

  def address
    [address_line1, address_line2, suburb, state, postcode, "Australia"].join(',')
  end

  def geocode_or_reset_coordinates
    if geocode.nil?
      self.latitude = nil
      self.longitude = nil
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:login]
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { in: 3..15 }
  has_one :profile, dependent: :destroy
  after_create :init_profile
  attr_writer :login

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def init_profile
    profile = Profile.new(user_id: self.id)
    profile.save(validate: false)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def account_owner?(subject)
    if user_signed_in? && current_user.profile.id == subject.profile_id
      true
    else
      false
    end
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
  def relationship(item)
    CartItem.find_by(listing_id: item.id)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
  def item_location(listing)
    geocode = Profile.find(listing.profile_id).to_coordinates
    location = Geocoder.search(geocode).first
    location.suburb + ", " + location.state
  end

  def img_for(listing)
    if listing.image.present?
      listing.image
    else
      'default.jpeg'
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  # #helper method to recall and fill stored cookie location for index page
  def stored_location
    if cookies[:lat_lon]
      geocode = JSON.parse cookies[:lat_lon]
      location = Geocoder.search(geocode).first
      suburb = location.suburb
      state = location.state
      if suburb == nil
        return state
      else
        suburb + ", " + state
      end
    end
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bokchoy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">  
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/nav" %>

    <%= yield %>

    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="coverbox">
  <img src="/assets/cover.jpg" width="100%" height="auto" alt="coverpage" />
  <div class="searchbox">
    <div class="container">
      <div style="margin: 5%;>
        <p class="text-muted">Enter your address to find your neighbours' produce</p>
        <form class="form-inline", action="/set_location", method="post">
          <input class="form-control m-sm-2" type="search" placeholder="123 New st, Newtown" aria-label="Search", name="address" required="required" minlength="8" value="<%= stored_location %>">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </div>
      </form>
    </div>
  </div>
</div>
<div class="card-deck">
  <div class="card" >
  <%= link_to listings_path(filter: 1) do %>
    <img src="assets/veggie.png" class="card-img-top" alt="..."style="width:13vw">
  <% end %>
  </div>
  <div class="card" >
  <%= link_to listings_path(filter: 2) do %>
    <img src="assets/fruits.png" class="card-img-top" alt="..."style="width:13vw">
  <% end %>
  </div>
  <div class="card" >
  <%= link_to listings_path(filter: 3) do %>
    <img src="assets/herbs.png" class="card-img-top" alt="..."style="width:13vw">
  <% end %>
  </div>
  <div class="card" >
  <%= link_to listings_path(filter: 4) do %>
    <img src="assets/eggs.png" class="card-img-top" alt="..."style="width:13vw">
  <% end %>
  </div>
  <div class="card" >
  <%= link_to listings_path(filter: 5) do %>
    <img src="assets/honey.png" class="card-img-top" alt="..."style="width:13vw">
  <% end %>
  </div>
  <div class="card" >
  <%= link_to listings_path(filter: 6) do %>
    <img src="assets/mushrooms.png" class="card-img-top" alt="..."style="width:13vw">
  <% end %>
  </div>
</div>
<div class="placeholder"></div>

app/views/shared/_accountmenu.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Account
  </a>
  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
    <%= link_to "Profile", profile_path(current_user.id), class: "dropdown-item" %> 
    <%= link_to "Message", messages_path, class: "dropdown-item" %> 
    <%= link_to "Order History", orders_path, class: "dropdown-item" %> 
    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %> 
  </div>
</li>

app/views/shared/_card.html.erb
<%= link_to listing, class:"text-decoration-none text-dark" do %>
<div class="card mb-3" style="max-width: 70vw;">
  <div class="row no-gutters">
    <div class="col-md-4" id="listing_img">
      <%= image_tag url_for(img_for(listing)) , alt: "#{listing.title} image", class: "card-img img-fluid"%>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= listing.title %></h5>
        <p class="card-text"><%= listing.description %></p>
        <p class="card-text"><small class="text-muted"><%= listing.created_at %></small></p>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:alert] %>
  <p class="alert alert-danger"><%= flash[:alert] %></p>
<% end %>
<% if flash[:success] %>
  <p class="alert alert-success"><%= flash[:success] %></p>
<% end %>

app/views/shared/_footer.html.erb
<nav class="navbar fixed-bottom navbar-light bg-success">
<ul class="navbar-nav ml-auto"><p class="font-italic">2020-2021</p></ul>
</nav>

app/views/shared/_form-errors.html.erb
<% if resource.errors.any? %>
  <div class="form-errors">
    <ul>  
        <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end  %>
    </ul>
  </div>
<% end %>

app/views/shared/_form_errors.html.erb
<% if resource.errors.any? %>
  <div class="form-errors">
    <ul>  
        <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end  %>
    </ul>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
  <%= link_to root_path, class: 'navbar-brand' do %> 

    <%= image_tag 'BClogo.png', size: '45x45' %>
    <span>BokChoy</span>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      <% unless user_signed_in? %>
      <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
      <% end %>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to "Create a listing", new_listing_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to cart_path, class: "nav-link" do %>
        <span>&#128722<span>
        <% end %>
      </li>
        <%= render "shared/accountmenu"%>
      <% else %>
        <li class="nav-item">
        <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
        <% end %>
        </li>
    </ul>
  </div>
</nav>
  <form class="form-inline" action="<%= root_path %>listings" role="search">
    <input class="form-control m-sm-2" type="search" placeholder="Search by title" aria-label="Search" name="search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit" >Search</button>
  </form>