config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  devise_for :users
  root to: 'pages#index'
  #home page to access to other area
  get 'profile/user/:id', to: 'profiles#show', as: 'profile'
  get 'profile/edit', to: 'profiles#edit'
  put 'profile', to: 'profiles#update'
  patch 'profile', to: 'profiles#update'
  match 'profile/user/:id' => 'profiles#update', via: :patch

  #user_profile should only be deleted if account is no longer exists
  resources :listings
  get 'cart', to: 'carts#show'
  resources :cart_items
  resources :messages
  get "/payments/session", to: "payments#get_stripe_id"
  post "/payments/webhook", to: "payments#webhook"
  get "/payments/success", to: "payments#success"
  resources :orders, only: [:index, :show]
  post "/set_location", to: "pages#set_location"
  get "/remove_location", to: "pages#remove_location"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can [:read, :create], Listing
    if user.present?
      can :manage, Listing, profile_id: user.profile.id
      can :manage, Profile, user_id: user.id
      if user.admin?
        can :manage, :all
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :profile
  has_many :cart_items
  has_many :listings, through: :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :listing
  validates :quantity, numericality: true, inclusion: { in: 1..100 }
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :profile, optional: true
  belongs_to :product
  has_one_attached :image
  has_many :messages
  has_many :cart_items
  has_many :carts, through: :cart_items
  validates :title, presence: true, length: { in: 3..40 }
  validates :description, presence: true, length: { in: 6..200 }
  validates :price, presence: true, numericality: true, inclusion: { in: 0.01..100 }

  enum delivery: { "Local Pickup": 1, "Delivery": 2, "Both": 3 }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: 'Profile', foreign_key: 'sender_id'
  belongs_to :recipient, class_name: 'Profile', foreign_key: 'recipient_id'
  belongs_to :listing, optional: true
  has_many :attached_messages, class_name: "Message", foreign_key: "thread_id"
  belongs_to :thread, class_name: "Message", optional: true
  validates :body, presence: true, length: { in: 3..500 }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :profile
  has_many :order_items, dependent: :destroy
  has_many :listings, through: :order_items

  enum delivery: { "Local Pickup": 1, "Delivery": 2 }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :listing
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :listings
  has_many :subcategories, class_name: "Product", foreign_key: "category_id"
  belongs_to :category, class_name: "Product", optional: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one :cart, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :listings
  validates :first_name, presence: true, length: { minimum: 2 }
  validates :last_name, presence: true, length: { minimum: 2 }
  validates :address_line1, presence: true, length: { minimum: 5 }
  validates :suburb, :state, presence: true
  validates :postcode, presence: true, length: { is: 4 }
  geocoded_by :address
  after_validation :geocode_or_reset_coordinates, if: :address_line1_changed?
  after_create :init_cart

  private

  def init_cart
    self.create_cart
  end

  def address
    [address_line1, address_line2, suburb, state, postcode, "Australia"].join(',')
  end

  def geocode_or_reset_coordinates
    if geocode.nil?
      self.latitude = nil
      self.longitude = nil
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:login]
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { in: 3..15 }
  has_one :profile, dependent: :destroy
  after_create :init_profile
  attr_writer :login

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def init_profile
    profile = Profile.new(user_id: self.id)
    profile.save(validate: false)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile, only: [:show]

  def show
    @cart = @profile.cart.listings.order(:title)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile
  def index
    @orders = @profile.orders
  end

  def show
    @order = Order.find(params[:id])
    ## Find an array of order_items with the corresponding listing details and the profile/user information linked to listing. Preloading associated tables in this step can minimize the query call when accessing the listing title and listing owner username in the view model.
    @order_items = OrderItem.includes(listing: { profile: :user }).where(order_id: params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:set_location]
  def index
  end

  ## Function to store user location to cookie
  def set_location
    rawdata = Geocoder.search("#{params[:address]}")
    if rawdata == []
      cookies.delete :lat_lon
      flash[:alert] = "Oops. I couldn't recognise this address. Please check."
    else
      rawdata = rawdata.first.coordinates
      cookies[:lat_lon] = JSON.generate(rawdata)
    end
    redirect_to listings_url
  end

  def remove_location
    cookies.delete :lat_lon
    redirect_to request.referer
end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def account_owner?(subject)
    if user_signed_in? && current_user.profile.id == subject.profile_id
      true
    else
      false
    end
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
  def relationship(item)
    CartItem.find_by(listing_id: item.id)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
  def item_location(listing)
    geocode = Profile.find(listing.profile_id).to_coordinates
    location = Geocoder.search(geocode).first
    location.suburb + ", " + location.state
  end

  def img_for(listing)
    if listing.image.present?
      listing.image
    else
      'default.jpeg'
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  # #helper method to recall and fill stored cookie location for index page
  def stored_location
    if cookies[:lat_lon]
      geocode = JSON.parse cookies[:lat_lon]
      location = Geocoder.search(geocode).first
      suburb = location.suburb
      state = location.state
      if suburb == nil
        return state
      else
        suburb + ", " + state
      end
    end
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/carts/_cart_table.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Quantity</th>
      <th scope="col">Price</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% total = 0%>
    <% cart.each do |item| %>
      <tr>
        <th scope="row">1</th>
        <td><%= link_to item.title, listing_path(item.id) %></td>
        <td><%= form_with model: relationship(item), local: true, method: :put do |form| %>
              <%= form.number_field :quantity, size: "3", step: 1 %>
              <%= form.hidden_field :listing_id, value: item.id %>
              <%= form.submit "Edit" %>
              <% end %>
          </td>
        <td><% subtotal = relationship(item).quantity * item.price %>
            <%= "$""%.2f" % subtotal%>
        </td>
        <% total += subtotal %>
        <td>
          <%= button_to "Delete", relationship(item), method: :delete %>
        </td>
        <% end %>
      </tr>
    <tr class="data-total-rows table-success">
      <td>Total</td>
      <td></td>
      <td></td>
      <td><strong><%= "$""%.2f" % total %></strong></td>
      <td></td>

    </tr>
    </tbody>
</table>

app/views/carts/show.html.erb
<div class="container">
  <h1>Shopping basket</h1>
  <% if @cart.length > 0 %>
  <%= render "cart_table", cart: @cart %>
  <div>
    <input type="radio" name="delivery" id="pickup" value=1 checked >
    <label for="pickup">Local Pickup</label>
    <input type="radio" name="delivery" id="delivery" value=2>
    <label for="delivery">Delivery</label><br>
  </div>
    <%# <% hidden_field_tag 'seller', item.profile.id %>
  <div>
    <%= link_to "Pay Now", "", id: "stripe", class: "btn btn-success float-right" %>  
  </div>
  <% else %>
  <%= "Your veggie box is currently empty, start shopping now" %>
  <% end %>
</div>

<% item = @cart.first %>

<%= javascript_pack_tag "stripe" %>
<div class="placeholder"></div>

app/views/orders/_order_table.html.erb
<table class="table">
  <thead>
    <tr class= "table-success">
      <th scope="col">Date of Purchase</th>
      <th scope="col">Amount Paid</th>
      <th scope="col">Method</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.created_at.to_formatted_s(:long) %></td>
        <td><%= "$""%.2f" % order.total_amount_paid %></td>
        <td><%= order.delivery %></td>
        <td><%= link_to "View details", order_path(order.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/index.html.erb
<div class="container">
  <h1>Purchase History</h1>
  <% if @orders.length > 0 %>
  <%= render 'order_table', order: @orders %>

    <% else %>
      <%= "No purchase recorded" %>
    <% end %>
</div>
<div class="placeholder"></div>

app/views/orders/show.html.erb
<div class="container">
  <h1>Order details</h1>
  <p class = "text-muted font-italic"><%= @order.created_at.to_formatted_s(:long) %></p>
  <table class="table table-sm">
    <thead>
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Quantity</th>
        <th scope="col">Price</th>
        <th scope="col">Seller</th>
      </tr>
    </thead>
    <tbody>
      <% @order_items.each do |item| %>
      <% listing = item.listing %>
      <tr>
        <td><%= link_to item.listing.title, listing_path(listing.id) %></td> 
        <td><%= item.quantity %></td>
        <td><%= "$""%.2f" % listing.price %></td>
        <td><%= link_to listing.profile.user.username, profile_path(listing.profile_id) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="placeholder"></div>